### ISSUE TITLE
GDB not working under Linux

### ISSUE THREAD

**Issue by becseya** [lvgl/lv_port_renesas_rx72n-envision-kit#1]
I'm having trouble starting the debugger with `RX72N_EnVision_LVGL HardwareDebug` configuration.

---

The following popup can be seen after pressing the *Debug* button:
![image](https://github.com/lvgl/lv_port_renesas_rx72n-envision-kit/assets/20841268/e39ef216-8a41-4456-908f-41ab3cec6834)
while console log shows:
```txt
GDB Server for Renesas targets.
	Version 9.5.0.v20240410-100424 [1a8868bc] (Apr 10 2024 20:15:54)


Starting server with the following options: 
        Raw options                : /home/akos/.eclipse/com.renesas.platform_2067645162/DebugComp//RX/e2-server-gdb -g E2LITE -t R5F572NN -uConnectionTimeout= 30 -uClockSrcHoco= 0 -uInputClock= 16 -uPTimerClock= 240000000 -uAllowClockSourceInternal= 1 -uUseFine= 1 -uFineBaudRate= 1.50 -w 0 -z 0 -uRegisterSetting= 0 -uModePin= 0 -uChangeStartupBank= 0 -uStartupBank= 0 -uDebugMode= 0 -uExecuteProgram= 0 -uIdCode= FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF -uresetOnReload= 1 -n 0 -uWorkRamAddress= 1000 -uverifyOnWritingMemory= 0 -uProgReWriteIRom= 0 -uProgReWriteDFlash= 0 -uhookWorkRamAddr= 0x7fb40 -uhookWorkRamSize= 0x4c0 -uOSRestriction= 0 -l -uCore= SINGLE_CORE|enabled|1|main -uSyncMode= async -uFirstGDB= main --english --gdbVersion= 12.1

Connecting to E2LITE, RX Target
        GDBServer endian           : little
        Target power from emulator : Off 
Starting target connection
GDB action 'connect to target', has failed with error report, can not connect to the emulator
Disconnected from the Target Debugger.

```

---

Both channels of SW1 were set to OFF, causing the `ACT` LED become green too (instead of only `POWER` LED being on after unboxing). *E2 Lite* is available as an USB device:
```bash
$ lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 015: ID 045b:82a0 Hitachi, Ltd E2 Lite
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
#...
```

**Comment by jeremy-baker** [comment]
The debug configuration connection settings should be :- 
![Screenshot from 2024-05-22 08-55-55](https://github.com/lvgl/lv_port_renesas_rx72n-envision-kit/assets/54705580/0eb5dbdf-e750-480c-a60c-8a8cd2c96f51)

**Comment by jeremy-baker** [comment]
Have you installed the Renesas E2 lite Linux driver :- 
https://www.renesas.com/us/en/document/swo/e2-emulator-e2-emulator-lite-linux-driver?r=488806

**Comment by jeremy-baker** [comment]
For completeness, the e2lite windows drivers are here :- 
https://www.renesas.com/us/en/document/uid/usb-driver-renesas-mcu-tools-v27700-64-bit-version-windows-os?r=488806

https://www.renesas.com/us/en/document/uid/usb-driver-renesas-mcu-toolse2e2-liteie850ie850apg-fp5-v27700for-32-bit-version-windows-os?r=488806

**Comment by becseya** [comment]
Debugging works after applying udev rules of the E2 Lite Linux driver (link above). Thanks @jeremy-baker
